'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VideoMinerInstall.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property setup() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("setup", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property VideoMiner_TemplateDatabase_Version_3_0_8() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VideoMiner_TemplateDatabase_Version_3_0_8", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;VideoMinerConfigurationDetails version=&quot;1&quot; revision=&quot;0&quot;&gt;
        '''  &lt;DetailedSpeciesEventConfiguration&gt;
        '''    &lt;Range&gt;
        '''      &lt;Displayed&gt;True&lt;/Displayed&gt;
        '''      &lt;DefaultValue&gt;NULL&lt;/DefaultValue&gt;
        '''    &lt;/Range&gt;
        '''    &lt;Side&gt;
        '''      &lt;DefaultValue&gt;0&lt;/DefaultValue&gt;
        '''    &lt;/Side&gt;
        '''    &lt;IDConfidence&gt;
        '''      &lt;Displayed&gt;True&lt;/Displayed&gt;
        '''      &lt;DefaultValue&gt;High&lt;/DefaultValue&gt;
        '''    &lt;/IDConfidence&gt;
        '''    &lt;Abundance&gt;
        '''      &lt;Displayed&gt;True&lt;/Displayed&gt;
        '''      &lt;DefaultValue&gt;Abundant&lt;/DefaultVa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VideoMinerConfigurationDetails() As String
            Get
                Return ResourceManager.GetString("VideoMinerConfigurationDetails", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property VideoMinerSetup() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VideoMinerSetup", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
